name: Basic validation description

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  enforce-pull-request:
    name: Enforce Pull Request Description Length
    uses: ryanvade/enforce-pr-description-length-action@v1
    with:
      minLength: 5
