name: Basic validation description

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  enforce-pull-request:
    runs-on: ubuntu-latest
    name: Enforce Pull Request Description Length
    steps:
      - uses:  ryanvade/enforce-pr-description-length-action@v1
        with:
         minLength: 5
      
